/**
 * Insights Service Catalog API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The JSONSchema model module.
* @module model/JSONSchema
* @version 1.0.0
*/
export default class JSONSchema {
    /**
    * Constructs a new <code>JSONSchema</code>.
    * @alias module:model/JSONSchema
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>JSONSchema</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/JSONSchema} obj Optional instance to populate.
    * @return {module:model/JSONSchema} The populated <code>JSONSchema</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JSONSchema();

            
            
            

            if (data.hasOwnProperty('schema')) {
                obj['schema'] = ApiClient.convertToType(data['schema'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {Object} schema
    */
    schema = undefined;








}


