/**
 * Insights Service Catalog API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import OrderItem from './OrderItem';





/**
* The Order model module.
* @module model/Order
* @version 1.0.0
*/
export default class Order {
    /**
    * Constructs a new <code>Order</code>.
    * @alias module:model/Order
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Order} obj Optional instance to populate.
    * @return {module:model/Order} The populated <code>Order</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Order();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('ordered_at')) {
                obj['ordered_at'] = ApiClient.convertToType(data['ordered_at'], 'Date');
            }
            if (data.hasOwnProperty('completed_at')) {
                obj['completed_at'] = ApiClient.convertToType(data['completed_at'], 'Date');
            }
            if (data.hasOwnProperty('order_items')) {
                obj['order_items'] = ApiClient.convertToType(data['order_items'], [OrderItem]);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} user_id
    */
    user_id = undefined;
    /**
    * Current State of the order
    * @member {module:model/Order.StateEnum} state
    */
    state = undefined;
    /**
    * @member {Date} created_at
    */
    created_at = undefined;
    /**
    * @member {Date} ordered_at
    */
    ordered_at = undefined;
    /**
    * @member {Date} completed_at
    */
    completed_at = undefined;
    /**
    * @member {Array.<module:model/OrderItem>} order_items
    */
    order_items = undefined;






    /**
    * Allowed values for the <code>state</code> property.
    * @enum {String}
    * @readonly
    */
    static StateEnum = {
    
        /**
         * value: "Created"
         * @const
         */
        "Created": "Created",
    
        /**
         * value: "Ordered"
         * @const
         */
        "Ordered": "Ordered",
    
        /**
         * value: "Failed"
         * @const
         */
        "Failed": "Failed",
    
        /**
         * value: "Completed"
         * @const
         */
        "Completed": "Completed"    
    };



}


