/**
 * Insights Service Catalog API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PortfolioItem model module.
* @module model/PortfolioItem
* @version 1.0.0
*/
export default class PortfolioItem {
    /**
    * Constructs a new <code>PortfolioItem</code>.
    * @alias module:model/PortfolioItem
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PortfolioItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PortfolioItem} obj Optional instance to populate.
    * @return {module:model/PortfolioItem} The populated <code>PortfolioItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PortfolioItem();

            
            
            

            if (data.hasOwnProperty('portfolio_id')) {
                obj['portfolio_id'] = ApiClient.convertToType(data['portfolio_id'], 'Number');
            }
            if (data.hasOwnProperty('favorite')) {
                obj['favorite'] = ApiClient.convertToType(data['favorite'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('orphan')) {
                obj['orphan'] = ApiClient.convertToType(data['orphan'], 'Boolean');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} portfolio_id
    */
    portfolio_id = undefined;
    /**
    * @member {Boolean} favorite
    */
    favorite = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Boolean} orphan
    */
    orphan = undefined;
    /**
    * @member {String} state
    */
    state = undefined;








}


