/**
 * Insights Service Catalog API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ProgressMessage model module.
* @module model/ProgressMessage
* @version 1.0.0
*/
export default class ProgressMessage {
    /**
    * Constructs a new <code>ProgressMessage</code>.
    * @alias module:model/ProgressMessage
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ProgressMessage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProgressMessage} obj Optional instance to populate.
    * @return {module:model/ProgressMessage} The populated <code>ProgressMessage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProgressMessage();

            
            
            

            if (data.hasOwnProperty('received_at')) {
                obj['received_at'] = ApiClient.convertToType(data['received_at'], 'Date');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('order_item_id')) {
                obj['order_item_id'] = ApiClient.convertToType(data['order_item_id'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Date} received_at
    */
    received_at = undefined;
    /**
    * @member {module:model/ProgressMessage.LevelEnum} level
    */
    level = undefined;
    /**
    * @member {String} message
    */
    message = undefined;
    /**
    * @member {String} order_item_id
    */
    order_item_id = undefined;






    /**
    * Allowed values for the <code>level</code> property.
    * @enum {String}
    * @readonly
    */
    static LevelEnum = {
    
        /**
         * value: "info"
         * @const
         */
        "info": "info",
    
        /**
         * value: "error"
         * @const
         */
        "error": "error",
    
        /**
         * value: "warning"
         * @const
         */
        "warning": "warning",
    
        /**
         * value: "debug"
         * @const
         */
        "debug": "debug"    
    };



}


