export const FETCH_CATALOG_ITEMS = 'FETCH_CATALOG_ITEMS';
export const FETCH_CATALOG_ITEM = 'FETCH_CATALOG_ITEM';
export const FILTER_CATALOG_ITEMS = 'FILTER_CATALOG_ITEMS';

export const FETCH_PROVIDER_DATA = 'FETCH_PROVIDER_DATA';
export const ADD_PROVIDER = 'ADD_PROVIDER';

export const FETCH_SERVICE_PLANS = 'FETCH_SERVICE_PLANS';
export const FETCH_SERVICE_PLAN_PARAMETERS = 'FETCH_SERVICE_PLAN_PARAMETERS';
export const UPDATE_SERVICE_DATA = 'UPDATE_SERVICE_DATA';
export const SUBMIT_SERVICE_ORDER = 'SUBMIT_SERVICE_ORDER';
export const SET_SERVICE_PLAN = 'SET_SERVICE_PLAN';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';