export const PLATFORM_DATA = 'FETCH_PLATFORM_DATA';
export const ADD_PLATFORM = 'ADD_PLATFORM';

export const FETCH_SERVICE_PLANS = 'FETCH_SERVICE_PLANS';
export const FETCH_SERVICE_PLAN_PARAMETERS = 'FETCH_SERVICE_PLAN_PARAMETERS';
export const UPDATE_SERVICE_DATA = 'UPDATE_SERVICE_DATA';
export const SUBMIT_SERVICE_ORDER = 'SUBMIT_SERVICE_ORDER';
export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN';
export const LIST_ORDERS = 'LIST_ORDERS';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const FETCH_PLATFORMS = 'FETCH_PLATFORMS';
export const FETCH_PLATFORM_ITEMS = 'FETCH_PLATFORM_ITEMS';
export const FETCH_PLATFORM_ITEM =  'FETCH_PLATFORM_ITEM;';
export const FILTER_PLATFORM_ITEMS = 'FILTER_PLATFORM_ITEMS';

export const FETCH_PORTFOLIOS = 'FETCH_PORTFOLIOS';
export const FETCH_PORTFOLIO_ITEMS = 'FETCH_PORTFOLIO_ITEMS';
export const FETCH_PORTFOLIO_ITEMS_WITH_PORTFOLIO = 'FETCH_PORTFOLIO_ITEMS_WITH_PORTFOLIO';
export const FETCH_PORTFOLIO = 'FETCH_PORTFOLIO';
export const FILTER_PORTFOLIO_ITEMS = 'FILTER_PORTFOLIO_ITEMS';
export const ADD_PORTFOLIO = 'ADD_PORTFOLIO';

