export const FETCH_SERVICE_PLANS = 'FETCH_SERVICE_PLANS';
export const FETCH_SERVICE_PLAN_PARAMETERS = 'FETCH_SERVICE_PLAN_PARAMETERS';
export const SUBMIT_SERVICE_ORDER = 'SUBMIT_SERVICE_ORDER';
export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN';
export const LIST_ORDERS = 'LIST_ORDERS';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const SET_ORDERS = 'SET_ORDERS';
export const FETCH_ORDERS = 'FETCH_ORDERS';

export const FETCH_PLATFORM = 'FETCH_PLATFORM';
export const FETCH_PLATFORMS = 'FETCH_PLATFORMS';
export const FETCH_PLATFORM_ITEMS = 'FETCH_PLATFORM_ITEMS';
export const FETCH_PLATFORM_ITEM = 'FETCH_PLATFORM_ITEM';
export const FETCH_MULTIPLE_PLATFORM_ITEMS = 'FETCH_MULTIPLE_PLATFORM_ITEMS';
export const FILTER_PLATFORM_ITEMS = 'FILTER_PLATFORM_ITEMS';
export const FETCH_PLATFORM_INVENTORIES = 'FETCH_PLATFORM_INVENTORIES';
export const SET_INVENTORIES_LOADING_STATE = 'SET_INVENTORIES_LOADING_STATE';

export const FETCH_PORTFOLIOS = 'FETCH_PORTFOLIOS';
export const FETCH_PORTFOLIO_ITEM = 'FETCH_PORTFOLIO_ITEM';
export const FETCH_PORTFOLIO_ITEMS = 'FETCH_PORTFOLIO_ITEMS';
export const FETCH_PORTFOLIO_ITEMS_WITH_PORTFOLIO =
  'FETCH_PORTFOLIO_ITEMS_WITH_PORTFOLIO';
export const FETCH_PORTFOLIO = 'FETCH_PORTFOLIO';
export const FILTER_PORTFOLIO_ITEMS = 'FILTER_PORTFOLIO_ITEMS';
export const ADD_PORTFOLIO = 'ADD_PORTFOLIO';
export const ADD_TO_PORTFOLIO = 'ADD_TO_PORTFOLIO';
export const UPDATE_PORTFOLIO = 'UPDATE_PORTFOLIO';
export const REMOVE_PORTFOLIO = 'REMOVE_PORTFOLIO';
export const REMOVE_PORTFOLIO_ITEMS = 'REMOVE_PORTFOLIO_ITEMS';
export const RESTORE_PORTFOLIO_ITEMS = 'RESTORE_PORTFOLIO_ITEMS';
export const RESET_SELECTED_PORTFOLIO = 'RESET_SELECTED_PORTFOLIO';
export const ADD_TEMPORARY_PORTFOLIO = 'ADD_TEMPORARY_PORTFOLIO';
export const UPDATE_TEMPORARY_PORTFOLIO = 'UPDATE_TEMPORARY_PORTFOLIO';
export const DELETE_TEMPORARY_PORTFOLIO = 'DELETE_TEMPORARY_PORTFOLIO';
export const RESTORE_PORTFOLIO_PREV_STATE = 'RESTORE_PORTFOLIO_PREV_STATE';
export const SET_PORTFOLIO_ITEMS = 'SET_PORTFOLIO_ITEMS';
export const UPDATE_TEMPORARY_PORTFOLIO_ITEM =
  'UPDATE_TEMPORARY_PORTFOLIO_ITEM';
export const RESTORE_PORTFOLIO_ITEM_PREV_STATE =
  'RESTORE_PORTFOLIO_ITEM_PREV_STATE';
export const UPDATE_PORTFOLIO_ITEM = 'UPDATE_PORTFOLIO_ITEM';

export const FETCH_RBAC_GROUPS = 'FETCH_RBAC_GROUPS';

export const SHARE_PORTFOLIO = 'SHARE_PORTFOLIO';
export const UNSHARE_PORTFOLIO = 'UNSHARE_PORTFOLIO';
export const QUERY_PORTFOLIO = 'QUERY_PORTFOLIO';

export const FETCH_REQUESTS = 'FETCH_REQUESTS';
export const FETCH_ORDER_ITEMS = 'FETCH_ORDER_ITEMS';

/**
 * Global redux loading state
 */
export const SET_LOADING_STATE = 'SET_LOADING_STATE';

/**
 * OpenApi action
 */
export const SET_OPENAPI_SCHEMA = '@@open-api/set-schema';

/**
 * Orders actions
 * TODO Prefix existing action types
 */
export const SET_ORDER_DETAIL = '@@orders/set-order-detail';
export const FETCH_APPROVAL_REQUESTS = '@@orders/fetch-order-requests';
export const FETCH_ORDER_PROVISION_ITEMS =
  '@@orders/FETCH_ORDER_PROVISION_ITEMS';
export const SET_ORDER_PROVISION_ITEMS = '@@orders/SET_ORDER_PROVISION_ITEMS';
/*
 * Portfolio actions
 */
export const SELECT_PORTFOLIO_ITEM = '@@portfolio/SELECT_PORTFOLIO_ITEM';

/**
 * Sources actions
 */
export const FETCH_SERVICE_OFFERING = '@@sources/FETCH_SERVICE_OFFERING';
export const SET_SOURCETYPE_ICONS = '@@sources/SET_SOURCETYPE_ICONS';
export const REFRESH_PLATFORM = '@@sources/REFRESH_PLATFORM';

/**
 * Breadcrumbs actions
 */
export const INITIALIZE_BREADCRUMBS = '@@breadcrumbs/INITIALIZE_BREADCRUMBS';

/**
 * In18l actions
 */

export const INITIALIZE_I18N = '@@i18l/INITIALIZE_I18N';

/*
 * Order processes actions
 */
export const FETCH_ORDER_PROCESSES = '@@order_processes/FETCH_ORDER_PROCESSES';
export const ADD_ORDER_PROCESS = '@@order_processes/ADD_ORDER_PROCESS';
export const SORT_ORDER_PROCESSES = '@@order_processes/SORT_ORDER_PROCESSES';
export const SET_ORDER_PROCESS = '@@order_processes/SET_ORDER_PROCESS';
export const FETCH_ORDER_PROCESS = '@@order_processes/FETCH_ORDER_PROCESS';
export const REMOVE_ORDER_PROCESS = '@@order_processes/REMOVE_ORDER_PROCESS';
export const REMOVE_ORDER_PROCESSES =
  '@@order_processes/REMOVE_ORDER_PROCESSES';
export const SET_FILTER_ORDER_PROCESSES =
  '@@order_processes/SET_FILTER_ORDER_PROCESSES';
export const UPDATE_ORDER_PROCESS = '@@order_process/UPDATE_ORDER_PROCESS';
