/**
 * Insights Service Catalog API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Portfolio from '../model/Portfolio';
import PortfolioItem from '../model/PortfolioItem';

/**
* Admins service.
* @module api/AdminsApi
* @version 1.0.0
*/
export default class AdminsApi {

    /**
    * Constructs a new AdminsApi. 
    * @alias module:api/AdminsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * API to add a new portfolio
     * Returns the added portfolio object 
     * @param {module:model/Portfolio} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    addPortfolioWithHttpInfo(body) {
      let postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addPortfolio");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/portfolios', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * API to add a new portfolio
     * Returns the added portfolio object 
     * @param {module:model/Portfolio} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    addPortfolio(body) {
      return this.addPortfolioWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * API to add a new portfolio item
     * Returns the added portfolio item object
     * @param {module:model/PortfolioItem} body
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    addPortfolioItemWithHttpInfo(body) {
      let postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addPortfolioItem");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/portfolio_items', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * API to add a new portfolio item
     * Returns the added portfolio item object
     * @param {module:model/PortfolioItem} body
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    addPortfolioItem(body) {
      return this.addPortfolioItemWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Add Portfolio item to a portfolio
     * Add new portfolio item to an existing portfolio
     * @param {Number} portfolioId The Portfolio ID
     * @param {Number} portfolioItemId The Portfolio Item ID
     * @param {module:model/PortfolioItem} item
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    addPortfolioItemToPortfolioWithHttpInfo(portfolioId, portfolioItemId, item) {
      let postBody = item;

      // verify the required parameter 'portfolioId' is set
      if (portfolioId === undefined || portfolioId === null) {
        throw new Error("Missing the required parameter 'portfolioId' when calling addPortfolioItemToPortfolio");
      }

      // verify the required parameter 'portfolioItemId' is set
      if (portfolioItemId === undefined || portfolioItemId === null) {
        throw new Error("Missing the required parameter 'portfolioItemId' when calling addPortfolioItemToPortfolio");
      }

      // verify the required parameter 'item' is set
      if (item === undefined || item === null) {
        throw new Error("Missing the required parameter 'item' when calling addPortfolioItemToPortfolio");
      }


      let pathParams = {
        'portfolio_id': portfolioId,
        'portfolio_item_id': portfolioItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/portfolios/{portfolio_id}/portfolio_items/{portfolio_item_id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Add Portfolio item to a portfolio
     * Add new portfolio item to an existing portfolio
     * @param {Number} portfolioId The Portfolio ID
     * @param {Number} portfolioItemId The Portfolio Item ID
     * @param {module:model/PortfolioItem} item
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    addPortfolioItemToPortfolio(portfolioId, portfolioItemId, item) {
      return this.addPortfolioItemToPortfolioWithHttpInfo(portfolioId, portfolioItemId, item)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetch a portfolio item from a specific portfolio
     * By passing in the portfolio id and portfolio_item_id you can fetch the portfolio items in the portfolio.
     * @param {Number} portfolioId The Portfolio ID
     * @param {Number} portfolioItemId The Portfolio Item ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PortfolioItem>} and HTTP response
     */
    fetchPortfolioItemFromPortfolioWithHttpInfo(portfolioId, portfolioItemId) {
      let postBody = null;

      // verify the required parameter 'portfolioId' is set
      if (portfolioId === undefined || portfolioId === null) {
        throw new Error("Missing the required parameter 'portfolioId' when calling fetchPortfolioItemFromPortfolio");
      }

      // verify the required parameter 'portfolioItemId' is set
      if (portfolioItemId === undefined || portfolioItemId === null) {
        throw new Error("Missing the required parameter 'portfolioItemId' when calling fetchPortfolioItemFromPortfolio");
      }


      let pathParams = {
        'portfolio_id': portfolioId,
        'portfolio_item_id': portfolioItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PortfolioItem];

      return this.apiClient.callApi(
        '/portfolios/{portfolio_id}/portfolio_items/{portfolio_item_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetch a portfolio item from a specific portfolio
     * By passing in the portfolio id and portfolio_item_id you can fetch the portfolio items in the portfolio.
     * @param {Number} portfolioId The Portfolio ID
     * @param {Number} portfolioItemId The Portfolio Item ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PortfolioItem>}
     */
    fetchPortfolioItemFromPortfolio(portfolioId, portfolioItemId) {
      return this.fetchPortfolioItemFromPortfolioWithHttpInfo(portfolioId, portfolioItemId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetch all portfolio items from a specific portfolio
     * By passing in the portfolio id you can fetch all the portfolio items in the portfolio.
     * @param {Number} portfolioId The Portfolio ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PortfolioItem>} and HTTP response
     */
    fetchPortfolioItemsWithPortfolioWithHttpInfo(portfolioId) {
      let postBody = null;

      // verify the required parameter 'portfolioId' is set
      if (portfolioId === undefined || portfolioId === null) {
        throw new Error("Missing the required parameter 'portfolioId' when calling fetchPortfolioItemsWithPortfolio");
      }


      let pathParams = {
        'portfolio_id': portfolioId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PortfolioItem];

      return this.apiClient.callApi(
        '/portfolios/{portfolio_id}/portfolio_items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetch all portfolio items from a specific portfolio
     * By passing in the portfolio id you can fetch all the portfolio items in the portfolio.
     * @param {Number} portfolioId The Portfolio ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PortfolioItem>}
     */
    fetchPortfolioItemsWithPortfolio(portfolioId) {
      return this.fetchPortfolioItemsWithPortfolioWithHttpInfo(portfolioId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetch a specific Portfolio
     * By passing in the portfolio id you can fetch a specific portfolio. 
     * @param {Number} portfolioId The Portfolio ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Portfolio} and HTTP response
     */
    fetchPortfolioWithIdWithHttpInfo(portfolioId) {
      let postBody = null;

      // verify the required parameter 'portfolioId' is set
      if (portfolioId === undefined || portfolioId === null) {
        throw new Error("Missing the required parameter 'portfolioId' when calling fetchPortfolioWithId");
      }


      let pathParams = {
        'portfolio_id': portfolioId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Portfolio;

      return this.apiClient.callApi(
        '/portfolios/{portfolio_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetch a specific Portfolio
     * By passing in the portfolio id you can fetch a specific portfolio. 
     * @param {Number} portfolioId The Portfolio ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Portfolio}
     */
    fetchPortfolioWithId(portfolioId) {
      return this.fetchPortfolioWithIdWithHttpInfo(portfolioId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * API to list portfolio_items
     * Returns an array of portfolio item objects
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PortfolioItem>} and HTTP response
     */
    listPortfolioItemsWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [PortfolioItem];

      return this.apiClient.callApi(
        '/portfolio_items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * API to list portfolio_items
     * Returns an array of portfolio item objects
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PortfolioItem>}
     */
    listPortfolioItems() {
      return this.listPortfolioItemsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * API to list portfolios
     * Returns an array of portfolio objects 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Portfolio>} and HTTP response
     */
    listPortfoliosWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [Portfolio];

      return this.apiClient.callApi(
        '/portfolios', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * API to list portfolios
     * Returns an array of portfolio objects 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Portfolio>}
     */
    listPortfolios() {
      return this.listPortfoliosWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
