/**
 * Insights Service Catalog API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CatalogItem from '../model/CatalogItem';
import CatalogPlan from '../model/CatalogPlan';
import JSONSchema from '../model/JSONSchema';
import Order from '../model/Order';
import OrderItem from '../model/OrderItem';
import PlanParameter from '../model/PlanParameter';
import Portfolio from '../model/Portfolio';
import PortfolioItem from '../model/PortfolioItem';
import ProgressMessage from '../model/ProgressMessage';

/**
* Users service.
* @module api/UsersApi
* @version 1.0.0
*/
export default class UsersApi {

    /**
    * Constructs a new UsersApi. 
    * @alias module:api/UsersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * fetches catalog items from all providers
     * Fetch catalog item from all defined providers 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit How many catalog items to return at one time (max 1000)
     * @param {Number} opts.offset Starting Offset (default to 0)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CatalogItem>} and HTTP response
     */
    catalogItemsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CatalogItem];

      return this.apiClient.callApi(
        '/catalog_items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * fetches catalog items from all providers
     * Fetch catalog item from all defined providers 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit How many catalog items to return at one time (max 1000)
     * @param {Number} opts.offset Starting Offset (default to 0)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CatalogItem>}
     */
    catalogItems(opts) {
      return this.catalogItemsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetches catalog parameters, it needs the provider id, the catalog_id and the plan_id
     * Return a JSON object with the parameters needed for a specific plan of a catalog item 
     * @param {String} providerId The Provider ID
     * @param {String} catalogId The Catalog ID
     * @param {String} planId The Plan ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PlanParameter>} and HTTP response
     */
    catalogPlanParametersWithHttpInfo(providerId, catalogId, planId) {
      let postBody = null;

      // verify the required parameter 'providerId' is set
      if (providerId === undefined || providerId === null) {
        throw new Error("Missing the required parameter 'providerId' when calling catalogPlanParameters");
      }

      // verify the required parameter 'catalogId' is set
      if (catalogId === undefined || catalogId === null) {
        throw new Error("Missing the required parameter 'catalogId' when calling catalogPlanParameters");
      }

      // verify the required parameter 'planId' is set
      if (planId === undefined || planId === null) {
        throw new Error("Missing the required parameter 'planId' when calling catalogPlanParameters");
      }


      let pathParams = {
        'provider_id': providerId,
        'catalog_id': catalogId,
        'plan_id': planId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PlanParameter];

      return this.apiClient.callApi(
        '/providers/{provider_id}/catalog_items/{catalog_id}/plans/{plan_id}/parameters', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetches catalog parameters, it needs the provider id, the catalog_id and the plan_id
     * Return a JSON object with the parameters needed for a specific plan of a catalog item 
     * @param {String} providerId The Provider ID
     * @param {String} catalogId The Catalog ID
     * @param {String} planId The Plan ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PlanParameter>}
     */
    catalogPlanParameters(providerId, catalogId, planId) {
      return this.catalogPlanParametersWithHttpInfo(providerId, catalogId, planId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetches catalog json schema, it needs the provider id, the catalog_id and the plan_id
     * Return a JSON schema with the parameters needed for a specific plan of a catalog item 
     * @param {String} providerId The Provider ID
     * @param {String} catalogId The Catalog ID
     * @param {String} planId The Plan ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/JSONSchema} and HTTP response
     */
    catalogPlanSchemaWithHttpInfo(providerId, catalogId, planId) {
      let postBody = null;

      // verify the required parameter 'providerId' is set
      if (providerId === undefined || providerId === null) {
        throw new Error("Missing the required parameter 'providerId' when calling catalogPlanSchema");
      }

      // verify the required parameter 'catalogId' is set
      if (catalogId === undefined || catalogId === null) {
        throw new Error("Missing the required parameter 'catalogId' when calling catalogPlanSchema");
      }

      // verify the required parameter 'planId' is set
      if (planId === undefined || planId === null) {
        throw new Error("Missing the required parameter 'planId' when calling catalogPlanSchema");
      }


      let pathParams = {
        'provider_id': providerId,
        'catalog_id': catalogId,
        'plan_id': planId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = JSONSchema;

      return this.apiClient.callApi(
        '/providers/{provider_id}/catalog_items/{catalog_id}/plans/{plan_id}/json_schema', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetches catalog json schema, it needs the provider id, the catalog_id and the plan_id
     * Return a JSON schema with the parameters needed for a specific plan of a catalog item 
     * @param {String} providerId The Provider ID
     * @param {String} catalogId The Catalog ID
     * @param {String} planId The Plan ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/JSONSchema}
     */
    catalogPlanSchema(providerId, catalogId, planId) {
      return this.catalogPlanSchemaWithHttpInfo(providerId, catalogId, planId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetch all or a specific catalog item from a specific provider
     * By passing in the provider id you can fetch all the catalog items in the provider. You can limit to a specific catalog item by passing its id 
     * @param {String} providerId The Provider ID
     * @param {Object} opts Optional parameters
     * @param {String} opts.catalogId The Catalog ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CatalogItem>} and HTTP response
     */
    fetchCatalogItemWithProviderWithHttpInfo(providerId, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'providerId' is set
      if (providerId === undefined || providerId === null) {
        throw new Error("Missing the required parameter 'providerId' when calling fetchCatalogItemWithProvider");
      }


      let pathParams = {
        'provider_id': providerId
      };
      let queryParams = {
        'catalog_id': opts['catalogId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CatalogItem];

      return this.apiClient.callApi(
        '/providers/{provider_id}/catalog_items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetch all or a specific catalog item from a specific provider
     * By passing in the provider id you can fetch all the catalog items in the provider. You can limit to a specific catalog item by passing its id 
     * @param {String} providerId The Provider ID
     * @param {Object} opts Optional parameters
     * @param {String} opts.catalogId The Catalog ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CatalogItem>}
     */
    fetchCatalogItemWithProvider(providerId, opts) {
      return this.fetchCatalogItemWithProviderWithHttpInfo(providerId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetches a specific catalog item for a provider
     * Fetch a catalog item by its ID and provider ID 
     * @param {String} providerId The Provider ID
     * @param {String} catalogId The Catalog ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CatalogItem>} and HTTP response
     */
    fetchCatalogItemWithProviderAndCatalogIDWithHttpInfo(providerId, catalogId) {
      let postBody = null;

      // verify the required parameter 'providerId' is set
      if (providerId === undefined || providerId === null) {
        throw new Error("Missing the required parameter 'providerId' when calling fetchCatalogItemWithProviderAndCatalogID");
      }

      // verify the required parameter 'catalogId' is set
      if (catalogId === undefined || catalogId === null) {
        throw new Error("Missing the required parameter 'catalogId' when calling fetchCatalogItemWithProviderAndCatalogID");
      }


      let pathParams = {
        'provider_id': providerId,
        'catalog_id': catalogId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CatalogItem];

      return this.apiClient.callApi(
        '/providers/{provider_id}/catalog_items/{catalog_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetches a specific catalog item for a provider
     * Fetch a catalog item by its ID and provider ID 
     * @param {String} providerId The Provider ID
     * @param {String} catalogId The Catalog ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CatalogItem>}
     */
    fetchCatalogItemWithProviderAndCatalogID(providerId, catalogId) {
      return this.fetchCatalogItemWithProviderAndCatalogIDWithHttpInfo(providerId, catalogId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetches all the plans for a specific catalog item for a provider
     * Fetch all plans for catalog item by its ID and provider ID 
     * @param {String} providerId The Provider ID
     * @param {String} catalogId The Catalog ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CatalogPlan>} and HTTP response
     */
    fetchPlansWithProviderAndCatalogIDWithHttpInfo(providerId, catalogId) {
      let postBody = null;

      // verify the required parameter 'providerId' is set
      if (providerId === undefined || providerId === null) {
        throw new Error("Missing the required parameter 'providerId' when calling fetchPlansWithProviderAndCatalogID");
      }

      // verify the required parameter 'catalogId' is set
      if (catalogId === undefined || catalogId === null) {
        throw new Error("Missing the required parameter 'catalogId' when calling fetchPlansWithProviderAndCatalogID");
      }


      let pathParams = {
        'provider_id': providerId,
        'catalog_id': catalogId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CatalogPlan];

      return this.apiClient.callApi(
        '/providers/{provider_id}/catalog_items/{catalog_id}/plans', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetches all the plans for a specific catalog item for a provider
     * Fetch all plans for catalog item by its ID and provider ID 
     * @param {String} providerId The Provider ID
     * @param {String} catalogId The Catalog ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CatalogPlan>}
     */
    fetchPlansWithProviderAndCatalogID(providerId, catalogId) {
      return this.fetchPlansWithProviderAndCatalogIDWithHttpInfo(providerId, catalogId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetch a portfolio item from a specific portfolio
     * By passing in the portfolio id and portfolio_item_id you can fetch the portfolio items in the portfolio.
     * @param {Number} portfolioId The Portfolio ID
     * @param {Number} portfolioItemId The Portfolio Item ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PortfolioItem>} and HTTP response
     */
    fetchPortfolioItemFromPortfolioWithHttpInfo(portfolioId, portfolioItemId) {
      let postBody = null;

      // verify the required parameter 'portfolioId' is set
      if (portfolioId === undefined || portfolioId === null) {
        throw new Error("Missing the required parameter 'portfolioId' when calling fetchPortfolioItemFromPortfolio");
      }

      // verify the required parameter 'portfolioItemId' is set
      if (portfolioItemId === undefined || portfolioItemId === null) {
        throw new Error("Missing the required parameter 'portfolioItemId' when calling fetchPortfolioItemFromPortfolio");
      }


      let pathParams = {
        'portfolio_id': portfolioId,
        'portfolio_item_id': portfolioItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PortfolioItem];

      return this.apiClient.callApi(
        '/portfolios/{portfolio_id}/portfolio_items/{portfolio_item_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetch a portfolio item from a specific portfolio
     * By passing in the portfolio id and portfolio_item_id you can fetch the portfolio items in the portfolio.
     * @param {Number} portfolioId The Portfolio ID
     * @param {Number} portfolioItemId The Portfolio Item ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PortfolioItem>}
     */
    fetchPortfolioItemFromPortfolio(portfolioId, portfolioItemId) {
      return this.fetchPortfolioItemFromPortfolioWithHttpInfo(portfolioId, portfolioItemId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetch all portfolio items from a specific portfolio
     * By passing in the portfolio id you can fetch all the portfolio items in the portfolio.
     * @param {Number} portfolioId The Portfolio ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PortfolioItem>} and HTTP response
     */
    fetchPortfolioItemsWithPortfolioWithHttpInfo(portfolioId) {
      let postBody = null;

      // verify the required parameter 'portfolioId' is set
      if (portfolioId === undefined || portfolioId === null) {
        throw new Error("Missing the required parameter 'portfolioId' when calling fetchPortfolioItemsWithPortfolio");
      }


      let pathParams = {
        'portfolio_id': portfolioId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PortfolioItem];

      return this.apiClient.callApi(
        '/portfolios/{portfolio_id}/portfolio_items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetch all portfolio items from a specific portfolio
     * By passing in the portfolio id you can fetch all the portfolio items in the portfolio.
     * @param {Number} portfolioId The Portfolio ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PortfolioItem>}
     */
    fetchPortfolioItemsWithPortfolio(portfolioId) {
      return this.fetchPortfolioItemsWithPortfolioWithHttpInfo(portfolioId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetch a specific Portfolio
     * By passing in the portfolio id you can fetch a specific portfolio. 
     * @param {Number} portfolioId The Portfolio ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Portfolio} and HTTP response
     */
    fetchPortfolioWithIdWithHttpInfo(portfolioId) {
      let postBody = null;

      // verify the required parameter 'portfolioId' is set
      if (portfolioId === undefined || portfolioId === null) {
        throw new Error("Missing the required parameter 'portfolioId' when calling fetchPortfolioWithId");
      }


      let pathParams = {
        'portfolio_id': portfolioId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Portfolio;

      return this.apiClient.callApi(
        '/portfolios/{portfolio_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetch a specific Portfolio
     * By passing in the portfolio id you can fetch a specific portfolio. 
     * @param {Number} portfolioId The Portfolio ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Portfolio}
     */
    fetchPortfolioWithId(portfolioId) {
      return this.fetchPortfolioWithIdWithHttpInfo(portfolioId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get an individual item from a given order
     * Get an item associated with an order. 
     * @param {String} orderId The Order ID
     * @param {String} orderItemId The Order Item ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OrderItem} and HTTP response
     */
    listOrderItemWithHttpInfo(orderId, orderItemId) {
      let postBody = null;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling listOrderItem");
      }

      // verify the required parameter 'orderItemId' is set
      if (orderItemId === undefined || orderItemId === null) {
        throw new Error("Missing the required parameter 'orderItemId' when calling listOrderItem");
      }


      let pathParams = {
        'order_id': orderId,
        'order_item_id': orderItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = OrderItem;

      return this.apiClient.callApi(
        '/orders/{order_id}/items/{order_item_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get an individual item from a given order
     * Get an item associated with an order. 
     * @param {String} orderId The Order ID
     * @param {String} orderItemId The Order Item ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OrderItem}
     */
    listOrderItem(orderId, orderItemId) {
      return this.listOrderItemWithHttpInfo(orderId, orderItemId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a list of items in a given order
     * Get a list of items associated with an order. 
     * @param {String} orderId The Order ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/OrderItem>} and HTTP response
     */
    listOrderItemsWithHttpInfo(orderId) {
      let postBody = null;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling listOrderItems");
      }


      let pathParams = {
        'order_id': orderId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [OrderItem];

      return this.apiClient.callApi(
        '/orders/{order_id}/items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get a list of items in a given order
     * Get a list of items associated with an order. 
     * @param {String} orderId The Order ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/OrderItem>}
     */
    listOrderItems(orderId) {
      return this.listOrderItemsWithHttpInfo(orderId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a list of orders
     * Get a list of orders associated with the logged in user. 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Order>} and HTTP response
     */
    listOrdersWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Order];

      return this.apiClient.callApi(
        '/orders', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get a list of orders
     * Get a list of orders associated with the logged in user. 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Order>}
     */
    listOrders() {
      return this.listOrdersWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * API to list portfolio_items
     * Returns an array of portfolio item objects
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PortfolioItem>} and HTTP response
     */
    listPortfolioItemsWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [PortfolioItem];

      return this.apiClient.callApi(
        '/portfolio_items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * API to list portfolio_items
     * Returns an array of portfolio item objects
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PortfolioItem>}
     */
    listPortfolioItems() {
      return this.listPortfolioItemsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * API to list portfolios
     * Returns an array of portfolio objects 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Portfolio>} and HTTP response
     */
    listPortfoliosWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [Portfolio];

      return this.apiClient.callApi(
        '/portfolios', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * API to list portfolios
     * Returns an array of portfolio objects 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Portfolio>}
     */
    listPortfolios() {
      return this.listPortfoliosWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a list of progress messages in an item
     * Get a list of progress messages associated with an order item. As the item is being processed the provider can update the progress messages 
     * @param {String} orderItemId The Order Item ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/ProgressMessage>} and HTTP response
     */
    listProgressMessagesWithHttpInfo(orderItemId) {
      let postBody = null;

      // verify the required parameter 'orderItemId' is set
      if (orderItemId === undefined || orderItemId === null) {
        throw new Error("Missing the required parameter 'orderItemId' when calling listProgressMessages");
      }


      let pathParams = {
        'order_item_id': orderItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AdminSecurity', 'UserSecurity'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ProgressMessage];

      return this.apiClient.callApi(
        '/order_items/{order_item_id}/progress_messages', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get a list of progress messages in an item
     * Get a list of progress messages associated with an order item. As the item is being processed the provider can update the progress messages 
     * @param {String} orderItemId The Order Item ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/ProgressMessage>}
     */
    listProgressMessages(orderItemId) {
      return this.listProgressMessagesWithHttpInfo(orderItemId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
