/**
 * Insights Service Catalog API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InsightsServiceCatalogApi);
  }
}(this, function(expect, InsightsServiceCatalogApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InsightsServiceCatalogApi.OrderItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderItem', function() {
    it('should create an instance of OrderItem', function() {
      // uncomment below and update the code to test OrderItem
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be.a(InsightsServiceCatalogApi.OrderItem);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property count (base name: "count")', function() {
      // uncomment below and update the code to test the property count
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property parameters (base name: "parameters")', function() {
      // uncomment below and update the code to test the property parameters
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property catalogId (base name: "catalog_id")', function() {
      // uncomment below and update the code to test the property catalogId
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property providerId (base name: "provider_id")', function() {
      // uncomment below and update the code to test the property providerId
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property orderId (base name: "order_id")', function() {
      // uncomment below and update the code to test the property orderId
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property orderedAt (base name: "ordered_at")', function() {
      // uncomment below and update the code to test the property orderedAt
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property completedAt (base name: "completed_at")', function() {
      // uncomment below and update the code to test the property completedAt
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

    it('should have the property externalRef (base name: "external_ref")', function() {
      // uncomment below and update the code to test the property externalRef
      //var instane = new InsightsServiceCatalogApi.OrderItem();
      //expect(instance).to.be();
    });

  });

}));
